import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import ClientOnly from '@/components/ClientOnly'
import RegisterModal from '@/components/models/RegisterModel'
import Modal from '@/components/models/Model'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <RegisterModal />
          {/* <Modal title='hello' isOpen /> */}
          <Navbar />
        </ClientOnly>

        {children}
        
        </body>
    </html>
  )
}
